# Generated by Django 3.2.5 on 2021-07-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_title', models.CharField(max_length=200, unique=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='side/sides_images')),
                ('side_description', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('side_iframe_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_description', models.TextField(max_length=300)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item/items_images')),
                ('slug', models.SlugField(max_length=200)),
                ('side_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.side')),
            ],
        ),
    ]
